### ISSUE TITLE
Paper on creative writing benchmark

### ISSUE THREAD

**Issue by AriMKatz** [EQ-bench/EQ-Bench#33]
Hi,

Is there a paper or more info on methodology for the creative writing benchmark?

**Comment by sam-paech** [comment]
Hello, no I haven't written a paper for the creative writing benchmark. Check out the [about page](https://eqbench.com/about.html) for some methodology info. The scoring rubric can be seen in the judge responses in the sample outputs. Otherwise, the code is here, and I'll be happy to answer any questions that you have.

**Comment by AriMKatz** [comment]
Ok thanks 👍
